services:
  - type: web
    name: peccioli-new-orleans
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run peccioli_neworleans_portal_v11.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
